name:  Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout code
        uses: actions/checkout@v4

      - name:  Setup SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name:  Deploy to Server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            cd /var/www/phishing-detection-system

            git pull origin main

            cd backend/api

            composer install --no-dev --optimize-autoloader

            php artisan migrate --force
            php artisan config:cache
            php artisan route:cache

            echo " Deployment complete"
          EOF